/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;
import com.barcodelib.barcode.Linear;
import java.awt.HeadlessException;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import koneksi.cls_pengeluaran;
import koneksi.conek;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author toshiba
 */
public class Pengeluaran extends javax.swing.JFrame {

    public Pengeluaran() {
        initComponents();
        kd_auto();
        ViewData();
    }
    
    public void kd_auto(){
        try {
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_inventory","root","");
            Statement stat = koneksi.createStatement();
            ResultSet rs = stat.executeQuery("SELECT MAX(kd_keluar) AS id FROM pengeluaran");
            while(rs.next()){
                Object[] obj = new Object[1];
                obj[0] = rs.getString("id");
                if(obj[0]==null){
                    obj[0]= "KLR000";
                }
                String str_kd = (String)obj[0];
                String kd = str_kd.substring(3,6);
                int int_code = Integer.parseInt(kd);
                int_code++;
                String a = String.format("%03d", int_code);
                String b = "KLR" + a;
                txtKd.setText(b);
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }      
     }
    
    public void ViewData(){
    cls_pengeluaran keluar = new cls_pengeluaran();
    try{
        jTable1.setModel(DbUtils.resultSetToTableModel(keluar.UpdateJTable()));
        
    }catch (Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void reset(){
        txtKd.setText(null);
        txtBuah.setText(null);
        txtTanggal.setText(null);
        txtJumlah.setText(null);
        txtKirim.setText(null);
        kd_auto();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txtKd = new javax.swing.JTextField();
        txtBuah = new javax.swing.JTextField();
        txtTanggal = new javax.swing.JTextField();
        txtCari = new javax.swing.JTextField();
        txtJumlah = new javax.swing.JTextField();
        txtKirim = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INVENTORY APP");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 204, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jButton1.setText("HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, 30));

        txtKd.setEnabled(false);
        txtKd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKdActionPerformed(evt);
            }
        });
        getContentPane().add(txtKd, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 130, 30));
        getContentPane().add(txtBuah, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 330, 30));
        getContentPane().add(txtTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 330, 30));

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });
        getContentPane().add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 290, 100, 30));
        getContentPane().add(txtJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, 90, 30));
        getContentPane().add(txtKirim, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 130, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kd_Buah", "Tanggal Keluar", "Jumlah", "Buah", "Dikirim Ke "
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 800, 130));

        btnSimpan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, 100, 40));

        btnEdit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, 100, 40));

        btnHapus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, 100, 40));

        btnCetak.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCetak.setText("Cetak");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });
        getContentPane().add(btnCetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, 100, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Pengeluaran.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        menuUtama menu = new menuUtama();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        cls_pengeluaran keluar = new cls_pengeluaran();
        keluar.kd_keluar = txtKd.getText();
        keluar.buah = txtBuah.getText();
        keluar.tgl_keluar = txtTanggal.getText();
        keluar.jumlah = txtJumlah.getText();
        keluar.kirim = txtKirim.getText();
        try{
            Linear barcode = new Linear();
            barcode.setType(Linear.CODE128B);
            barcode.setData(txtKd.getText());
            barcode.setI(11.0f);
            String fname = txtKd.getText();
            barcode.renderBarcode("src/Barcode_Pengeluaran/" + fname + ".png");
            keluar.submit();
            ViewData();
            reset();
            JOptionPane.showMessageDialog(null, "Data dan Barcode Berhasil disimpan");
        } catch (SQLException ex) {
            Logger.getLogger(Penyimpanan.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Pengeluaran.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row =jTable1.getSelectedRow();
        txtKd.setText(jTable1.getModel().getValueAt(row, 0).toString());
        txtTanggal.setText(jTable1.getModel().getValueAt(row, 1).toString());
        txtBuah.setText(jTable1.getModel().getValueAt(row, 2).toString());
        txtJumlah.setText(jTable1.getModel().getValueAt(row, 3).toString());
        txtKirim.setText(jTable1.getModel().getValueAt(row, 4).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try{
            String sql = "INSERT pengeluaran set kd_keluar = '"+txtKd.getText()+"' ,tgl_keluar='"+txtTanggal.getText()+"' ,buah='"+txtBuah.getText()+"' ,jumlah='"+txtJumlah.getText()+"' ,dikirim='"+txtKirim.getText()+"' On Duplicate Key Update kd_keluar ='"+txtKd.getText()+"' ,tgl_keluar='"+txtTanggal.getText()+"' ,buah='"+txtBuah.getText()+"' ,jumlah='"+txtJumlah.getText()+"' ,dikirim='"+txtKirim.getText()+"'"; 
            java.sql.Connection conn = (Connection)conek.GetConnection();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Edit data berhasil");
        }
        catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        ViewData();
        reset();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        String ObjButtons[]= {"Ya","Tidak"};
        int PromptResult = JOptionPane.showOptionDialog(null, "hapus ?", "Message", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, ObjButtons, ObjButtons[1]);
        if(PromptResult==0){
            cls_pengeluaran klr = new cls_pengeluaran();
            klr.kd_keluar = txtKd.getText();
            try{
                klr.hapus();
                JOptionPane.showMessageDialog(null, "Berhasil dihapus");
                ViewData();
                reset();
            }
            catch (Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        // TODO add your handling code here:
        String buah = txtCari.getText();
        cls_pengeluaran klr = new cls_pengeluaran();
        try{
            jTable1.setModel(DbUtils.resultSetToTableModel(klr.SearchTextList(buah)));
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_txtCariKeyReleased

    private void txtKdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKdActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        try {
            File namaFile = new File("src/laporan/report_pengeluaran.jasper");
            JasperPrint jp = JasperFillManager.fillReport(namaFile.getPath(), null, conek.GetConnection());
            JasperViewer.viewReport(jp,false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnCetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pengeluaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtBuah;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtKd;
    private javax.swing.JTextField txtKirim;
    private javax.swing.JTextField txtTanggal;
    // End of variables declaration//GEN-END:variables
}
